FROM node:22-alpine
WORKDIR /app
ENV NODE_ENV=production

# install server deps
COPY server/package*.json ./
RUN npm ci --omit=dev

# copy server sources
COPY server/ ./

# If the backend listens on a configurable port, set PORT via env in K8s
EXPOSE 3001
CMD ["node","index.js"]
