apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rconnect-data
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # storageClassName: <your-storage-class>   # optionally pin your SC
---
apiVersion: v1
kind: Service
metadata:
  name: rcon
  namespace: minecraft
  labels:
    app: rconnect
spec:
  type: ClusterIP
  selector:
    app: rconnect
  ports:
    - name: http
      port: 80
      targetPort: web
    # Optional: expose backend internally too (handy for debugging/automation)
    - name: api
      port: 3001
      targetPort: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rconnect
  namespace: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rconnect
  template:
    metadata:
      labels:
        app: rconnect
    spec:
      securityContext:
        fsGroup: 10001
      containers:
        - name: web
          image: <registry>/rconnect-web:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: web
              containerPort: 3000
          env:
            # Helpful default so the UI can reach the backend in the same Pod
            # If the UI does not support this, ignore it; users can still enter the URL manually.
            - name: RCONNECT_BACKEND_URL
              value: "http://127.0.0.1:3001"
          readinessProbe:
            tcpSocket:
              port: web
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: web
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi

        - name: api
          image: <registry>/rconnect-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: api
              containerPort: 3001
          env:
            # If server/index.js supports PORT, set it here. Otherwise remove.
            - name: PORT
              value: "3001"

            # If you later adapt backend to read these automatically:
            # - name: RCON_HOST
            #   value: "bohnsdorfcraft-1-minecraft.minecraft.svc.cluster.local"
            # - name: RCON_PORT
            #   value: "25575"
            # - name: RCON_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: rconnect-secrets
            #       key: rcon_password

          volumeMounts:
            - name: data
              mountPath: /data
          readinessProbe:
            tcpSocket:
              port: api
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: api
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: rconnect-data
